version: '3'

services:
  web:
    image: web
    environment:
      - ALLOW_OVERRIDE=true
    ports:
      - "81:80"
    links:
      - db
    volumes:
      - ./app:/var/www/html/
    user: "root:1000"
      
  db:
    image: mariadb:10.8.2
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ISSKS
      MYSQL_PASSWORD: LANA2
      MYSQL_DATABASE: database
    ports:
      - "8889:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    links:
      - db
    ports:
      - 8890:80
    environment:
      MYSQL_USER: ISSKS
      MYSQL_PASSWORD: LANA2
      MYSQL_DATABASE: database

